---
- name: Install GitLab CLI
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes

  tasks:
    - name: 1. Get latest GitLab CLI release info
      uri:
        url: "https://gitlab.com/api/v4/projects/gitlab-org%2Fcli/releases?per_page=1&order_by=released_at&sort=desc"
        return_content: yes
      register: glab_release

    - name: 2. Set glab download URL
      set_fact:
        glab_deb_url: "{{ glab_release.json[0].assets.links | selectattr('name', 'match', 'glab_.*_linux_amd64\\.deb') | map(attribute='url') | first }}"

    - name: 3. Download GitLab CLI .deb package
      get_url:
        url: "{{ glab_deb_url }}"
        dest: /tmp/glab_linux_amd64.deb
        force: yes

    - name: 4. Install GitLab CLI .deb package
      apt:
        deb: /tmp/glab_linux_amd64.deb
        state: present

    - name: 5. Remove downloaded .deb package
      file:
        path: /tmp/glab_linux_amd64.deb
        state: absent
